name: 'CrowdStrike Cloud IaC Scanning'
description: 'Assess security risks in your infrastructure as code (IaC) before applications are deployed using the FCS CLI tool. '
author: 'ryan.payne@crowdstrike'

inputs:
  target-directory:
    description: 'Directory you want to scan, ./ to scan all'
    required: true
    default: './'

outputs:
  output1:
    description: ''
    value: ''

runs:
  using: composite
  steps:
    - run: mkdir -p crowdstrike/$GITHUB_RUN_ID
      shell: bash
    - run: tar -xvzf $GITHUB_ACTION_PATH/fcs_0.34.0_Linux_x86_64.tar.gz
      shell: bash
    - run: chmod +x fcs
      shell: bash
    - run: ./fcs iac scan --path ${{ inputs.target-directory }} --report-formats json --output-path ./crowdstrike/$GITHUB_RUN_ID
      shell: bash
